--ALTER SESSION SET CURRENT_SCHEMA=SSPBMGR;

-- Using readable names for now 
--- TODO: use Banner naming standards if this has to be Banner specific

Prompt Page Role

 CREATE TABLE PAGE_ROLE 
   (ID NUMBER(19,0) NOT NULL ,
   PAGE_ID NUMBER(19,0) NOT NULL ,
	VERSION NUMBER(19,0) NOT NULL , 
	ALLOW NUMBER(1,0) NOT NULL , 
	ROLE_NAME VARCHAR2(30 CHAR) NOT NULL , 
	 PRIMARY KEY (ID) , 
	 CONSTRAINT PAGE_ROLE_FK1 FOREIGN KEY (PAGE_ID)
	  REFERENCES PAGE (ID) 
   );
   
   CREATE INDEX PAGE_ROLE_FK1_IDX ON PAGE_ROLE (PAGE_ID);
   
   CREATE OR REPLACE PUBLIC SYNONYM PAGE_ROLE FOR PAGE_ROLE;
   GRANT ALL ON PAGE_ROLE TO BANINST1;   