--ALTER SESSION SET CURRENT_SCHEMA=SSPBMGR;

-- Using readable names for now 
--- TODO: use Banner naming standards if this has to be Banner specific

Prompt Page

  CREATE TABLE PAGE  (
    CONSTANT_NAME VARCHAR2(60 CHAR) NOT NULL,
	MODEL_VIEW CLOB NOT NULL, 
	COMPILED_VIEW CLOB,
	COMPILED_CONTROLLER CLOB,
	ID NUMBER(19,0) NOT NULL, 
	VERSION NUMBER(19,0) NOT NULL, 
	EXTENDS_PAGE_ID NUMBER(19),
    --	 
    PRIMARY KEY (ID),
    UNIQUE(CONSTANT_NAME)
   ); 
   
   ALTER TABLE PAGE
      ADD CONSTRAINT EXTENDS_PAGE_FK1 FOREIGN KEY (EXTENDS_PAGE_ID)
	  REFERENCES PAGE (ID) ;
   CREATE OR REPLACE PUBLIC SYNONYM PAGE FOR PAGE;
   GRANT ALL ON PAGE TO BANINST1;