--ALTER SESSION SET CURRENT_SCHEMA=SSPBMGR;

-- Using readable names for now 
--- TODO: use Banner naming standards if this has to be Banner specific

Prompt Requestmap for spring security

CREATE TABLE REQUESTMAP (
    ID NUMBER(19,0) NOT NULL, 
	VERSION NUMBER(19,0) NOT NULL, 
	CONFIG_ATTRIBUTE VARCHAR2(4000 CHAR) NOT NULL, 
	URL VARCHAR2(255 CHAR) NOT NULL, 
	 PRIMARY KEY (ID), 
	 UNIQUE (URL)
);

CREATE OR REPLACE PUBLIC SYNONYM REQUESTMAP FOR REQUESTMAP;
GRANT ALL ON REQUESTMAP TO BANINST1;