--ALTER SESSION SET CURRENT_SCHEMA=SSPBMGR;

-- Using readable names for now 
--- TODO: use Banner naming standards if this has to be Banner specific

Prompt Page

  CREATE TABLE PAGE  (
    CONSTANT_NAME VARCHAR2(60 CHAR) NOT NULL,
	MODEL_VIEW CLOB NOT NULL, 
	COMPILED_VIEW CLOB, 
	ID NUMBER(19,0) NOT NULL, 
	VERSION NUMBER(19,0) NOT NULL, 
    --	 
    PRIMARY KEY (ID),
    UNIQUE(CONSTANT_NAME)
   ); 
   
   CREATE OR REPLACE PUBLIC SYNONYM PAGE FOR PAGE;
   GRANT ALL ON PAGE TO BANINST1;