--ALTER SESSION SET CURRENT_SCHEMA=SSPBMGR;

-- Using readable names for now 
--- TODO: use Banner naming standards if this has to be Banner specific

Prompt Css Role

 CREATE TABLE CSS_ROLE
   (ID NUMBER(19,0) NOT NULL ,
   CSS_ID NUMBER(19,0) NOT NULL ,
	VERSION NUMBER(19,0) NOT NULL , 
	ALLOW NUMBER(1,0) NOT NULL , 
	ROLE_NAME VARCHAR2(30 CHAR) NOT NULL , 
	 PRIMARY KEY (ID) , 
	 CONSTRAINT CSS_ROLE_FK1 FOREIGN KEY (CSS_ID)
	  REFERENCES CSS (ID)
   );
   
   CREATE OR REPLACE PUBLIC SYNONYM CSS_ROLE FOR CSS_ROLE;
   GRANT ALL ON CSS_ROLE TO BANINST1;