--
-- page_role2.sql
--
-- AUDIT TRAIL: PB9.0.0                      INIT       DATE
-- 1.                                          HvT      2016-06-08
--    PROJECT: PB
--    OBJECT:  PAGE_ROLE
--    TYPE:    COMMENT
--    DESCRIPTION:
--    Table with PageBuilder Page roles
--    PURPOSE:
--    This table stores the roles associated with PageBuilder Pages
--    TODO Review/Correct Detailed Description and purpose of Object
-- AUDIT TRAIL END
--
COMMENT ON TABLE PAGE_ROLE  IS
'Table with PageBuilder Page roles';
COMMENT ON COLUMN PAGE_ROLE.ID IS
'Id generated by sequence';
COMMENT ON COLUMN PAGE_ROLE.PAGE_ID IS
'Pagent Page Id';
COMMENT ON COLUMN PAGE_ROLE.VERSION IS
'Version';
COMMENT ON COLUMN PAGE_ROLE.ALLOW IS
'Role is allowed to view the page 0 for False, 1 for True';
COMMENT ON COLUMN PAGE_ROLE.ROLE_NAME IS
'Role Name - In Banner this references a web tailor role';
