--
-- page2.sql
--
-- AUDIT TRAIL: PB9.0.0                      INIT       DATE
-- 1.                                          HvT      2016-06-08
--    PROJECT: PB
--    OBJECT:  PAGE
--    TYPE:    COMMENT
--    DESCRIPTION:
--    Table with PageBuilder Pages
--    PURPOSE:
--    This table stores the PageBuilder Pages
--    TODO Review/Correct Detailed Description and purpose of Object
-- AUDIT TRAIL END
--
COMMENT ON TABLE PAGE  IS
'Table with PageBuilder Pages';
COMMENT ON COLUMN PAGE.CONSTANT_NAME IS
'Name of Page';
COMMENT ON COLUMN PAGE.MODEL_VIEW IS
'Page Model';
COMMENT ON COLUMN PAGE.COMPILED_VIEW IS
'Compiled Page View';
COMMENT ON COLUMN PAGE.COMPILED_CONTROLLER IS
'Compiled Page Controller';
COMMENT ON COLUMN PAGE.ID IS
'Id generated by sequence';
COMMENT ON COLUMN PAGE.VERSION IS
'Version';
COMMENT ON COLUMN PAGE.EXTENDS_PAGE_ID IS
'Page being extended aka the base page for this page';
COMMENT ON COLUMN PAGE.DATE_CREATED IS
'Date Created';
COMMENT ON COLUMN PAGE.LAST_UPDATED IS
'Date Updated';
COMMENT ON COLUMN PAGE.FILE_TIMESTAMP IS
'File timestamp used in export and import';
