--
-- requestmap2.sql
--
-- AUDIT TRAIL: PB9.0.0                      INIT       DATE
-- 1.                                          HvT      2016-06-08
--    PROJECT: PB
--    OBJECT:  REQUESTMAP
--    TYPE:    COMMENT
--    DESCRIPTION:
--    Requestmap table for Spring Security
--    PURPOSE:
--    This table stores the RequestMap data for Spring with SecurityConfigType.Requestmap
--    TODO Review/Correct Detailed Description and purpose of Object
-- AUDIT TRAIL END
--
COMMENT ON TABLE REQUESTMAP  IS
'Requestmap table for Spring Security ';
COMMENT ON COLUMN REQUESTMAP.ID IS
'Id generated by sequence';
COMMENT ON COLUMN REQUESTMAP.VERSION IS
'Version';
COMMENT ON COLUMN REQUESTMAP.CONFIG_ATTRIBUTE IS
'Spring security attributes for url';
COMMENT ON COLUMN REQUESTMAP.URL IS
'Url secured with configured attributes';
