--
-- virtual_domain2.sql
--
-- AUDIT TRAIL: PB9.0.0                      INIT       DATE
-- 1.                                          HvT      2016-06-08
--    PROJECT: PB
--    OBJECT:  VIRTUAL_DOMAIN
--    TYPE:    COMMENT
--    DESCRIPTION:
--    Table with PageBuilder Virtual Domains
--    PURPOSE:
--    This table stores the PageBuilder Virtual Domains
--    TODO Review/Correct Detailed Description and purpose of Object
-- AUDIT TRAIL END
--
COMMENT ON TABLE VIRTUAL_DOMAIN  IS
'Table with PageBuilder Virtual Domains';
COMMENT ON COLUMN VIRTUAL_DOMAIN.SERVICE_NAME IS
'Restful Service name defined in this record';
COMMENT ON COLUMN VIRTUAL_DOMAIN.TYPE_OF_CODE IS
'Type of code. S for SQL. Other code type is currently not implemented.';
COMMENT ON COLUMN VIRTUAL_DOMAIN.CODE_GET IS
'Statement to retrieve a collection of records. To support update and delete a record should have an id field.';
COMMENT ON COLUMN VIRTUAL_DOMAIN.CODE_DELETE IS
'Statement to delete record identified by id.';
COMMENT ON COLUMN VIRTUAL_DOMAIN.CODE_POST IS
'Statement to Create a new record';
COMMENT ON COLUMN VIRTUAL_DOMAIN.CODE_PUT IS
'Statement to modify record identified by id.';
COMMENT ON COLUMN VIRTUAL_DOMAIN.ID IS
'Id generated by sequence';
COMMENT ON COLUMN VIRTUAL_DOMAIN.VERSION IS
'Version';
COMMENT ON COLUMN VIRTUAL_DOMAIN.DATE_CREATED IS
'Date created';
COMMENT ON COLUMN VIRTUAL_DOMAIN.LAST_UPDATED IS
'Date updated';
COMMENT ON COLUMN VIRTUAL_DOMAIN.FILE_TIMESTAMP IS
'File timestamp - used in export and import';
