--
-- virtual_domain_role2.sql
--
-- AUDIT TRAIL: PB9.0.0                      INIT       DATE
-- 1.                                          HvT      2016-06-08
--    PROJECT: PB
--    OBJECT:  VIRTUAL_DOMAIN_ROLE
--    TYPE:    COMMENT
--    DESCRIPTION:
--    Table with PageBuilder Virtual Domain Roles
--    PURPOSE:
--    This table stores the roles and privileges associated with PageBuilder Virtual Domains
--    TODO Review/Correct Detailed Description and purpose of Object
-- AUDIT TRAIL END
--
COMMENT ON TABLE VIRTUAL_DOMAIN_ROLE  IS
'Table with PageBuilder Virtual Domain Roles';
COMMENT ON COLUMN VIRTUAL_DOMAIN_ROLE.ID IS
'Id generated by sequence';
COMMENT ON COLUMN VIRTUAL_DOMAIN_ROLE.VERSION IS
'Version';
COMMENT ON COLUMN VIRTUAL_DOMAIN_ROLE.ALLOW_DELETE IS
'Role is allowed to delete from the virtual domain. 0 for false, 1 for true';
COMMENT ON COLUMN VIRTUAL_DOMAIN_ROLE.ALLOW_GET IS
'Role is allowed to get from the virtual domain. 0 for false, 1 for true';
COMMENT ON COLUMN VIRTUAL_DOMAIN_ROLE.ALLOW_POST IS
'Role is allowed to post to the virtual domain. 0 for false, 1 for true';
COMMENT ON COLUMN VIRTUAL_DOMAIN_ROLE.ALLOW_PUT IS
'Role is allowed to put to the virtual domain. 0 for false, 1 for true';
COMMENT ON COLUMN VIRTUAL_DOMAIN_ROLE.ROLE_NAME IS
'Role Name - In Banner this references a web tailor role';
COMMENT ON COLUMN VIRTUAL_DOMAIN_ROLE.VIRTUAL_DOMAIN_ID IS
'Virtual Domain to which this role applies';
